
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIGIT LOWERCASE SPECIAL UPPERCASEpassword : characterscharacters : character characters\n    | charactercharacter : UPPERCASE\n    | LOWERCASE\n    | DIGIT\n    | SPECIAL'

_lr_action_items = {'UPPERCASE':([0,3,4,5,6,7,],[4,4,-4,-5,-6,-7,]),'LOWERCASE':([0,3,4,5,6,7,],[5,5,-4,-5,-6,-7,]),'DIGIT':([0,3,4,5,6,7,],[6,6,-4,-5,-6,-7,]),'SPECIAL':([0,3,4,5,6,7,],[7,7,-4,-5,-6,-7,]),'$end':([1,2,3,4,5,6,7,8,],[0,-1,-3,-4,-5,-6,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'password':([0,],[1,]),'characters':([0,3,],[2,8,]),'character':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> password","S'",1,None,None,None),
  ('password -> characters','password',1,'p_password','parser.py',9),
  ('characters -> character characters','characters',2,'p_characters','parser.py',26),
  ('characters -> character','characters',1,'p_characters','parser.py',27),
  ('character -> UPPERCASE','character',1,'p_character','parser.py',54),
  ('character -> LOWERCASE','character',1,'p_character','parser.py',55),
  ('character -> DIGIT','character',1,'p_character','parser.py',56),
  ('character -> SPECIAL','character',1,'p_character','parser.py',57),
]
